CREATE TABLE hobbies
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        varchar(255) NOT NULL,
    CONSTRAINT hobbies_pk PRIMARY KEY (id)
);

INSERT INTO hobbies (id,name) VALUES
(1, 'Hobis1'),
(2, 'Hobis2'),
(3, 'Hobis3'),
(4, 'Hobis4');

SELECT SETVAL('public.hobbies_id_seq', COALESCE(MAX(id), 1) ) FROM public.hobbies;