CREATE TABLE chats
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT chats_pk      PRIMARY KEY (id)
);

INSERT INTO chats (id) VALUES
(1),
(2),
(3);


SELECT SETVAL('public.chats_id_seq', COALESCE(MAX(id), 1) ) FROM public.chats;


CREATE TABLE couples
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        TIMESTAMPTZ,
    weight_diff FLOAT,
    first       BIGINT,
    second      BIGINT,
    status      couple_status,
    chat        BIGINT,
    CONSTRAINT couple_pk      PRIMARY KEY (id),
    FOREIGN KEY(first) 
      REFERENCES users(id),
    FOREIGN KEY(second) 
      REFERENCES users(id),
    FOREIGN KEY(chat) 
      REFERENCES chats(id)
);

INSERT INTO couples (id, date, weight_diff, first, second, status, chat) VALUES
(1, '2023-04-29 10:54:17.851+00', 15, 1, 2, 'LIKES', 1),
(2, '2023-04-29 10:54:17.851+00', 15, 3, 4, 'DISLIKES', 2),
(3, '2023-04-29 10:54:17.851+00', 15, 5, 6, 'UNDECIDED', 3);

SELECT SETVAL('public.couples_id_seq', COALESCE(MAX(id), 1) ) FROM public.couples;


CREATE TABLE messages
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content             TEXT,
    date                TIMESTAMPTZ,
    sender              BIGINT,
    chat                BIGINT,
    CONSTRAINT messages_pk      PRIMARY KEY (id),
    FOREIGN KEY(sender) 
      REFERENCES users(id),
    FOREIGN KEY(chat) 
      REFERENCES chats(id)  
);

INSERT INTO messages (id, content, date, sender, chat) VALUES
(1, 'Labas', '2023-04-29 10:54:17.851+00', 1, 1),
(2, 'NZN', '2023-04-29 10:54:27.851+00', 1, 1),
(3, 'sdfsdfsdf', '2023-04-29 10:54:37.851+00', 2, 1),
(4, 'sq', '2023-04-29 10:54:47.851+00', 1, 1),
(5, 'NZasdasdN', '2023-04-29 10:54:57.851+00', 1, 1),
(6, 'sdfsdxczxczxcfsdf', '2023-04-29 10:54:59.851+00', 2, 1);

SELECT SETVAL('public.messages_id_seq', COALESCE(MAX(id), 1) ) FROM public.messages;