CREATE TABLE events
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date              TIMESTAMPTZ,
    end_date                TIMESTAMPTZ,
    title                   VARCHAR(255),
    lattitude               VARCHAR(255),
    longitude               VARCHAR(255),
    user_id                 BIGINT,
    CONSTRAINT event_pk      PRIMARY KEY (id),
    FOREIGN KEY(user_id)
        REFERENCES users(id)
);

INSERT INTO events (id, start_date, end_date, title, lattitude, longitude, user_id) VALUES
(1, '2023-04-29 01:01:00.000+00', '2023-04-29 01:01:00.000+00', 'Marathon', '54.6911694', '25.4662231', 1),
(2, '2023-04-28 01:01:00.000+00', null, 'Interview', '54.6911694', '25.4662231', 2),
(3, '2023-04-29 01:01:00.000+00', null, 'Birthday', '54.6911694', '25.4662231', 1);

SELECT SETVAL('public.events_id_seq', COALESCE(MAX(id), 1) ) FROM public.events;