DROP TABLE IF EXISTS hobbies;

CREATE TABLE hobbies
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        varchar(255) NOT NULL
);

INSERT INTO hobbies (id,name) VALUES
(1, 'Hobis1'),
(2, 'Hobis2'),
(3, 'Hobis3'),
(4, 'Hobis4');