DROP TABLE IF EXISTS hobbies;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS couple;

CREATE TYPE couple_status AS ENUM 
('LIKES', 'DISLIKES', 'UNDECIDED');

CREATE TYPE roles AS ENUM
('ADMIN', 'USER');

CREATE TYPE genders AS ENUM 
('MALE', 'FEMALE', 'OTHER');

CREATE TYPE search_genders AS ENUM
('MALE', 'FEMALE', 'OTHER', 'ANY');

CREATE TYPE purposes AS ENUM
('SHORT', 'LONG');


CREATE TABLE hobbies
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        varchar(255) NOT NULL,
    CONSTRAINT hobbies_pk PRIMARY KEY (id)
);

INSERT INTO hobbies (id,name) VALUES
(1, 'Hobis1'),
(2, 'Hobis2'),
(3, 'Hobis3'),
(4, 'Hobis4');

SELECT SETVAL('public.hobbies_id_seq', COALESCE(MAX(id), 1) ) FROM public.hobbies;


CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    surname             VARCHAR(255),
    email               VARCHAR(255),
    password            VARCHAR(255),
    phone               VARCHAR(255),
    role                roles,
    birth_date          TIMESTAMPTZ,
    gender              genders,
    height              INT,
    picture             VARCHAR(255),
    description         TEXT,
    search_gender       search_genders,
    radius              INT,
    points              INT,
    block_end           TIMESTAMPTZ,
    blocked             BOOLEAN,
    star_sign           VARCHAR(255),
    personality_type    VARCHAR(255),
    love_language       VARCHAR(255),
    match_purpose       purposes,
  	CONSTRAINT users_pk PRIMARY KEY (id)
);

INSERT INTO users (id, name, surname, email, password, phone, role, birth_date, gender, height, picture, description, search_gender, radius, points, block_end, blocked, star_sign, personality_type, love_language, match_purpose) VALUES
(1, 'pirmas', 'pirmasis', 'pirmas@gmail.com', 'pirmas', '123456789', 'USER', '2023-04-29 10:54:17.851+00', 'MALE', '182', '', 'description', 'FEMALE', '50', '0', null, false, 'Aries', 'idk', 'idk2', 'LONG'),
(2, 'antras', 'antrasis', 'antras@gmail.com', 'antras', '123456789', 'USER', '2023-04-29 10:54:17.851+00', 'MALE', '175', '', 'description', 'FEMALE', '50', '0', null, false, 'Aries', 'idk', 'idk2', 'LONG'),
(3, 'trecia', 'trecioji', 'pirmas@gmail.com', 'trecia', '123456789', 'USER', '2023-04-29 10:54:17.851+00', 'FEMALE', '170', '', 'description', 'FEMALE', '50', '0', null, false, 'Aries', 'idk', 'idk2', 'LONG'),
(4, 'ketvirta', 'ketvirtoji', 'pirmas@gmail.com', 'ketvirta', '123456789', 'USER', '2023-04-29 10:54:17.851+00', 'FEMALE', '172', '', 'description', 'FEMALE', '50', '0', null, false, 'Aries', 'idk', 'idk2', 'LONG'),
(5, 'penktas', 'penktasis', 'penktas@gmail.com', 'penktas', '123456789', 'USER', '2023-04-29 10:54:17.851+00', 'MALE', '172', '', 'description', 'MALE', '50', '0', null, false, 'Aries', 'idk', 'idk2', 'LONG'),
(6, 'sesta', 'sestoji', 'pirmas@gmail.com', 'sesta', '123456789', 'USER', '2023-04-29 10:54:17.851+00', 'FEMALE', '160', '', 'description', 'FEMALE', '50', '0', null, false, 'Aries', 'idk', 'idk2', 'LONG');


SELECT SETVAL('public.users_id_seq', COALESCE(MAX(id), 1) ) FROM public.users;

CREATE TABLE couple
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        TIMESTAMPTZ,
    weight_diff FLOAT,
    first       BIGINT,
    second      BIGINT,
    status      couple_status,
    CONSTRAINT couple_pk      PRIMARY KEY (id),
    FOREIGN KEY(first) 
      REFERENCES users(id),
    FOREIGN KEY(second) 
      REFERENCES users(id)
);

INSERT INTO couple (id, date, weight_diff, first, second, status) VALUES
(1, '2023-04-29 10:54:17.851+00', 15, 1, 2, 'LIKES'),
(2, '2023-04-29 10:54:17.851+00', 15, 3, 4, 'DISLIKES'),
(3, '2023-04-29 10:54:17.851+00', 15, 5, 6, 'UNDECIDED');

SELECT SETVAL('public.couple_id_seq', COALESCE(MAX(id), 1) ) FROM public.couple;